// <auto-generated />
namespace Gestao__de_Contrato.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ConfiguracaoDasTabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfiguracaoDasTabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "202102202104029_ConfiguracaoDasTabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
